version: '3.8'

services:
  ui:
    build: ./ui
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/workspace/shared
    environment:
      - API_URL=http://converter:5000
      - VITIS_URL=http://vitis:6000
    depends_on:
      - converter

  converter:
    build: ./converter
    volumes:
      - shared-data:/workspace/shared
    expose:
      - "5000"

  vitis:
    build: ./vitis
    privileged: true
    volumes:
      - shared-data:/workspace/shared
    expose:
      - "6000"

volumes:
  shared-data:
